config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  controller :people do
    post '/people/set_preferred/:id' => :set_preferred, as: :people_set_preferred
  end
  resources :people
  resources :automobiles
  resources :licenses
  controller :rents do
    get '/rents/calculate_cost' => :calculate_cost, as: :rents_calculate_cost
    post '/rents/pickup_car/:id' => :pickup_car, as: :rents_pickup_car
    post '/rents/return_car/:id' => :return_car, as: :rents_return_car
  end
  resources :rents

  root 'rents#index'
  get '*path' => redirect('/')
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  belongs_to :preferred_phone, class_name: 'Phone', optional: true
  has_many :phones, dependent: :destroy
  accepts_nested_attributes_for :phones, allow_destroy: true
  has_many :rents
  has_one :license, dependent: :destroy
  accepts_nested_attributes_for :license

  validates_presence_of :name, :email, :document, :birth_date
  validates_uniqueness_of :document

  scope :ordered, -> { order('people.created_at desc') }
  scope :order_name, -> { order('people.name asc') }
  scope :age_between, lambda { |from_age, to_age|
    if from_age.present? && to_age.present?
      where(birth_date: (Date.today - to_age.to_i.year)..(Date.today - from_age.to_i.year))
    end
  }

  ransacker :age, formatter: proc { |v| Date.today - v.to_i.year } do |parent|
    parent.table[:birth_date]
  end

  after_commit :set_preferred_phone, if: -> { preferred_phone.blank? && phones.any? }

  def full_name
    "#{name} #{last_name}"
  end

  def set_preferred_phone
    update(preferred_phone_id: phones.first&.id)
  end

  def set_preferred!(phone_id)
    update(preferred_phone_id: phone_id)
  end

  def age
    ((Time.zone.now - birth_date.to_time) / 1.year.seconds).floor
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy set_preferred]

  def index
    @q = Person.ransack(params[:q])
    @people = @q.result
    filter_by_modalities if params.dig(:q, :license, :modalities_ids)
  end

  def edit
    @person.build_license if @person.license.blank?
  end

  def set_preferred
    if @person.set_preferred!(params[:phone_id])
      redirect_to request.referrer, notice: 'Atualizado com sucesso!'
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def update
    if @person.update(person_params)
    end
    respond_to do |format|
      format.js
    end
  end

  def new
    @person = Person.new
    @person.build_license if @person.license.blank?
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to edit_person_path(@person), notice: "#{@person.name} criado com sucesso!"
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy; end

  private

  def filter_by_modalities
    array = params[:q][:license][:modalities_ids]&.reject!(&:blank?)
    if array.present?
      @people = @people.where(id: License.where('modalities_ids @> ARRAY[?]::integer[]', array).select(&:person_id))
     end
  end

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :last_name, :document, :email, :birth_date, :preferred_phone_id,
                                   phones_attributes: %i[id number ddd kind person_id _destroy],
                                   license_attributes: [:id, :number, :expiration, :person_id, { modalities_ids: [] }])
  end
end

app/views/people/_form.html.erb
<%= form_for [@person], remote: true, multiple: true do |f| %>
  <div class="row">
    <div class="input-field col s12 m6 l4">
      <%= f.text_field :name %>
      <label for="person_name">Nome</label>
    </div>
    <div class="input-field col s12 m6 l4">
      <%= f.text_field :last_name %>
      <label for="person_last_name">Sobrenome</label>
    </div>
    <div class="input-field col s12 m6 l4">
      <%= f.text_field :email %>
      <label for="person_email">E-mail</label>
    </div>
    <div class="input-field col s12 m6 l6">
      <%= f.text_field :birth_date, type: "date" %>
      <label for="person_birth_date">Data de Nascimento</label>
    </div>
    <div class="input-field col s12 m6 l6">
      <%= f.text_field :document %>
      <label for="person_last_document">Documento</label>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m12 l12">
      <h5 class="orange-text f20">Adicionar Telefone</h5>
      <div class="input-field">
        <%= f.fields_for :phones do |phone| %>
          <%= render 'phone_fields', f: phone %>
        <% end %>
      </div>
      <div class="form-group">
        <%= link_to_add_association "<i class='material-icons'>add</i>".html_safe, f, :phones, class: 'btn green' %>
      </div>
    </div>
  </div>
  <h5 class="blue-text f20">Habilitação</h5>
  <div class="card">
    <div class="card-content">
      <div class="row">
        <%= f.fields_for :license do |l| %>
          <div class="input-field col s12 m6 l4">
            <%= l.text_field :number %>
            <label for="license_number">Número</label>
          </div>
          <div class="input-field col s12 m6 l4">
            <%= l.text_field :expiration, type: "date" %>
            <label for="license_expiration">Validade</label>
          </div>
          <div class="input-field col s12 m6 l4">
            <%= l.collection_select :modalities_ids, Modality.all, :id, :category, {:include_hidden => true}, {multiple: true} %>
            <%= l.label :modalities_ids, "Modalidades" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="action">
      <button type="submit" class="btn blue right"><%= @person.new_record? ? 'Criar' : 'Atualizar' %></button>
    </div>
  </div>
<% end %>

app/views/people/_list.html.erb
<table class="striped responsive-table f12">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Documento</th>
      <th>Nascimento</th>
      <th>E-mail</th>
      <th>Fone</th>
      <th>Habilitação?</th>
      <th>#</th>
    </tr>
  </thead>
  <tbody>
    <%= render @people %>
  </tbody>
</table>

app/views/people/_person.html.erb
<tr>
  <td>
    <%= person.full_name %>
  </td>
  <td>
    <%= person.document %>
  </td>
  <td>
    <%= person.birth_date %>
  </td>
  <td>
    <%= person.email %>
  </td>
  <td>
    <%= person.preferred_phone&.full_number %>
  </td>
  <td>
    <%= person_license_valid(person) %>
  </td>
  <td>
    <%= link_to edit_person_path(person) do %>
      <i class="material-icons f20">edit</i>
    <% end %>
  </td>
</tr>

app/views/people/_phone_fields.html.erb
<div class="nested-fields">
  <div class="card">
    <div class="card-content">
      <div class="row">
        <div class="col s12 m12 l6">
          <div class="row">
            <div class="col s12 m12 l3">
              <div class="input-field">
                <%= f.text_field :ddd, maxlength: 2, placeholder: "DDD" %>
              </div>
            </div>
            <div class="col s12 m12 l9">
              <div class="input-field">
                <%= f.text_field :number, maxlength: 9, placeholder: "Número" %>
              </div>
            </div>
          </div>
        </div>
        <div class="col s12 m12 l5">
          <div class="input-field">
            <%= f.text_field :kind %>
            <label class="active">Tipo</label>
          </div>
        </div>
        <div class="col s12 m12 l1">
          <div class="field ">
            <div class="form-group border-top">
              <% unless @person.new_record? %>
                <%= link_to "<i class='material-icons amber-text'>#{f.object == @person.preferred_phone ? 'star' : 'star_border'}</i>".html_safe, people_set_preferred_path(id: @person.id, phone_id: f.object.id), class: "btn white", method: "post" %>
              <% end %>
              <%= link_to_remove_association "<i class='material-icons white-text'>delete_sweep</i>".html_safe, f, class: 'btn  red darken-1' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/people/create.js.erb
<% if @person.errors.any? %>
  <% @person.errors.full_messages.each do |msg| %>
    M.toast({html: '<%= msg %>', classes: 'red'});
  <% end %>
<% else %>
  M.toast({html: 'Criado!', classes: 'green'});
<% end %>

app/views/people/edit.html.erb
<div class="card">
  <div class="card-content">
  <h5 class="blue-text f20">Edit # <%= @person.id %></h5>
    <%= render "form" %>
  </div>
</div>

app/views/people/index.html.erb
<div class="card">
  <div class="card-content">
    <%= search_form_for @q, remote: true do |f| %>
      <div class="row">
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :id_eq  %>
            <%= f.label :id_eq, "Código" %>
          </div>
        </div>
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :name_or_last_name_cont  %>
            <%= f.label :name_or_last_name_cont, "Nome" %>
          </div>
        </div>
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :email_cont  %>
            <%= f.label :email_cont, "E-mail" %>
          </div>
        </div>
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :document_cont  %>
            <%= f.label :document_cont, "Document" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12 m12 l3">
          <div class="input-field">
            <%= f.search_field :age_lteq  %>
            <%= f.label :age_lteq, "Idade maior que" %>
          </div>
        </div>
        <div class="col s12 m12 l3">
          <div class="input-field">
            <%= f.select :loyal_eq, [["Selecione", ''], ["Fidelizado", true], ["Não fidelizado", false]] %> 
            <%= f.label :loyal_eq, "Fidelizado" %>
          </div>
        </div>
        <div class="col s12 m6 l3">
          <%= f.fields_for :license do |l| %>
            <div class="input-field">
              <%= l.collection_select :modalities_ids, Modality.all, :id, :category, {:include_hidden => true}, {multiple: true} %>
              <%= l.label :modalities_ids, "Modalidades" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col s12 m12 l12">
          <%= f.submit 'buscar', :class => 'btn shadow blue right', :id => "buscar" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="card">
  <div class="card-content">
    <%= link_to "Novo", new_person_path, class: "btn green" %>
    <div id="people_list">
      <%= render "list" %>
    </div>
  </div>
</div>

app/views/people/index.js.erb
$("#people_list").html("<%= j( render 'list' )%>");
M.toast({html: '<%= pluralize(@people.size, "resultado", "resultados") %>', classes: 'grey'});

app/views/people/new.html.erb
<div class="card">
  <div class="card-content">
  <h5 class="blue-text f20">Novo Cliente</h5>
    <%= render "form" %>
  </div>
</div>

app/views/people/update.js.erb
<% if @person.errors.any? %>
  <% @person.errors.full_messages.each do |msg| %>
    M.toast({html: '<%= msg %>', classes: 'red'});
  <% end %>
<% else %>
  M.toast({html: 'Atualizado!', classes: 'green'});
<% end %>