config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  controller :people do
    post '/people/set_preferred/:id' => :set_preferred, as: :people_set_preferred
  end
  resources :people
  resources :automobiles
  resources :licenses
  controller :rents do
    get '/rents/calculate_cost' => :calculate_cost, as: :rents_calculate_cost
    post '/rents/pickup_car/:id' => :pickup_car, as: :rents_pickup_car
    post '/rents/return_car/:id' => :return_car, as: :rents_return_car
  end
  resources :rents

  root 'rents#index'
  get '*path' => redirect('/')
end

app/models/rent.rb
# frozen_string_literal: true

class Rent < ApplicationRecord
  belongs_to :person
  belongs_to :automobile

  validates_presence_of :start_date, :end_date
  validates :cost, numericality: { greater_than: 0 }

  validate :check_rules, on: :create

  scope :ordered, -> { order('rents.created_at desc') }
  scope :completeds, -> { where.not(return_date: nil) }

  before_validation :set_cost
  after_update_commit :set_loyal

  def pickup!
    update(pickup_date: Date.today)
  end

  def return!
    update(return_date: Date.today)
  end

  def set_loyal
    person.update(loyal: true) if person&.rents&.completeds&.count.to_i >= 2
  end

  def set_cost
    days = end_date - start_date
    self.cost = automobile&.cost.to_f * days
  rescue Exception => e
    errors.add(:erro, e)
  end

  def check_rules
    if person&.rents&.where(return_date: nil)&.any?
      errors.add(:erro, '~> cliente possui locação pendente')
    end
    if person.present? && (person&.age <= 21)
      errors.add(:erro, '~> idade insuficiente para alugar qualquer automóvel.')
    end
    if automobile&.motorcycle? && person.license&.modalities_ids&.exclude?(1)
      errors.add(:erro, '~> cliente não possui habilitação de moto.')
    end
    if (automobile&.car? || automobile&.vuc?) && person.license&.modalities_ids&.exclude?(2)
      errors.add(:erro, '~> cliente não possui habilitação de carro/vuc')
    end
    if automobile&.bus? && (person&.age <= 40)
      errors.add(:erro, '~> idade insuficiente para alugar ônibus.')
    end
    if automobile&.bus? && person.license&.modalities_ids&.exclude?(4)
      errors.add(:erro, '~> cliente não possui habilitação de ônibus.')
    end
    if automobile&.truck? && (person&.age <= 60)
      errors.add(:erro, '~> idade insuficiente para alugar caminhão.')
    end
    if automobile&.truck? && person.license&.modalities_ids&.exclude?(3)
      errors.add(:erro, '~> cliente não possui habilitação de caminhão.')
    end
    if end_date.present? && start_date.present? && (((end_date.to_time - start_date.to_time) / 1.day.seconds).floor >= 4) && (person&.rents&.completeds&.count.to_i < 2)
      errors.add(:erro, '~> tempo de locação muito longa.')
    end
    if person&.license&.expired?
      errors.add(:erro, '~> Habilitação está expirada.')
    end
    if start_date.present? && start_date.to_time.wednesday? && (automobile.license_plate[-1] == '4')
      errors.add(:erro, '~> Este automóvel não pode ser alugado hoje.')
    end
    if automobile.present? && automobile.rents.where(return_date: nil).any?
      errors.add(:erro, '~> Este automóvel já está alugado.')
    end
    errors&.any?
  end
end

app/controllers/rents_controller.rb
# frozen_string_literal: true

class RentsController < ApplicationController
  before_action :set_rent, only: %i[show edit update destroy pickup_car return_car]

  def index
    @q = Rent.ransack(params[:q])
    @rents = @q.result
  end

  def edit; end

  def pickup_car
    @rent.pickup!
  end

  def return_car
    @rent.return!
  end

  def calculate_cost
    get_cost(params[:start_date].to_date, params[:end_date].to_date, Automobile.find(params[:automobile_id]).cost)
  end

  def update
    @rent.update(rent_params)
    respond_to do |format|
      format.js
    end
  end

  def new
    @rent = Rent.new
  end

  def create
    @rent = Rent.new(rent_params)
    if @rent.save
      redirect_to edit_rent_path(@rent), notice: "Locação #{@rent.automobile.license_plate} #{@rent.person.full_name} criado com sucesso!"
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy; end

  private

  def get_cost(start_date, end_date, cost)
    days = end_date - start_date
    @cost = cost * days
  rescue Exception => e
  end

  def set_rent
    @rent = Rent.find(params[:id])
  end

  def rent_params
    params.require(:rent).permit(:person_id, :automobile_id, :cost, :start_date, :end_date, :pickup_date, :delivery_date)
  end
end

app/views/rents/_form.html.erb
<%= form_for [@rent], remote: true do |f| %>
  <div class="row">
    <div class="input-field col s12 m12 l6">
      <%= f.collection_select :person_id, Person.all.order_name, :id, :full_name, { prompt: "Selecione" } %>
      <%= f.label :person, "Cliente" %>
    </div>
    <div class="input-field col s12 m6 l6">
      <%= f.collection_select :automobile_id, Automobile.all, :id, :full_description, { prompt: "Selecione" }, {id: "select_automobile"} %>
      <%= f.label :automobile_id, "Automóvel" %>
    </div>
    <div class="input-field col s12 m6 l6">
      <%= f.text_field :start_date, type: "date", id: "start_date" %>
      <%= f.label :start_date, "Data de Início" %>
    </div>
    <div class="input-field col s12 m6 l6">
      <%= f.text_field :end_date, type: "date", id: "end_date" %>
      <%= f.label :end_date, "Data de Término" %>
    </div>
    <div class="input-field col s12 m6 l6">
      <%= f.text_field :cost, placeholder: "R$", :readonly => "true", id: "cost" %>
      <%= f.label :cost, "Custo" %>
    </div>
    <div class="col s12 m6 l6">
      <a id="calculate_cost" class="btn purple">Calcular</a>
    </div>
  </div>
  <% unless @rent.new_record? %>
    <div class="row">
      <div class="input-field col s12 m6 l6">
        <%= f.text_field :pickup_date, type: "date", id: "pickup_date" %>
        <%= f.label :pickup_date, "Data de Retirada" %>
      </div>
      <div class="input-field col s12 m6 l6">
        <%= f.text_field :return_date, type: "date", id: "return_date" %>
        <%= f.label :return_date, "Data de Entrega" %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="action">
      <button type="submit" class="btn blue right"><%= @rent.new_record? ? 'Criar' : 'Atualizar' %></button>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $("#calculate_cost").click(function(){
    var automobile_id = $("#select_automobile").val();
    var start_date = $("#start_date").val();
    var end_date = $("#end_date").val();
    $.ajax( {
      url: "/rents/calculate_cost",
      method: "get",
      dataType: "script",
      data: {
        'automobile_id':        automobile_id,
        'start_date':       start_date,
        'end_date':         end_date
      },
      error: function(e){
        return M.toast({html: 'Não foi possível fazer a requisição. (Code: '+e.status+')', classes: 'red'});
      }
    });
  });
</script>

app/views/rents/_list.html.erb
<div class="row">
  <div class="col s12 m12 l3 offset-l9">
    <strong class="grafit-text f20">Custo Total: </strong>
    <span class="green-text f20"><%= @rents.sum("cost") %></span>
  </div>
</div>
<table class="striped responsive-table f12">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Automóvel</th>
      <th>Início</th>
      <th>Fim</th>
      <th>Retirada</th>
      <th>Entrega</th>
      <th><%= sort_link @q, :cost, "Custo", {}, { :remote => true } %></th>
      <th>Status</th>
      <th>#</th>
    </tr>
  </thead>
  <tbody>
    <%= render @rents %>
  </tbody>
</table>

app/views/rents/_rent.html.erb
<tr>
  <td>
    <%= rent.person.full_name %>
  </td>
  <td>
    <%= rent.automobile.model %>
  </td>
  <td>
    <%= custom_date rent.start_date %>
  </td>
  <td>
    <%= custom_date rent.end_date %>
  </td>
  <td>
    <% if rent.pickup_date.blank? %>
      <%= link_to "Retirar", rents_pickup_car_path(rent), class: "btn small green", method: "post", remote: true, data: { confirm: "Você tem certeza?" } %>
    <% else %>
      <%= custom_date rent.pickup_date %>
    <% end %>
  </td>
  <td>
    <% if rent.return_date.blank? %>
      <%= link_to "Entregar", rents_return_car_path(rent), class: "btn small green", method: "post", remote: true, data: { confirm: "Você tem certeza?" }, disabled: rent.pickup_date.blank? %>
    <% else %>
      <%= custom_date rent.return_date %>
    <% end %>
  </td>
  <td class="green-text">
    <%= "R$ #{rent.cost}" %>
  </td>
  <td>
    <%= status(rent) %>
  </td>
  <td>
    <%= link_to edit_rent_path(rent) do %>
      <i class="material-icons f20">edit</i>
    <% end %>
  </td>
</tr>

app/views/rents/calculate_cost.js.erb
<% if @erro.present? %>
  M.toast({html: 'Não foi possível fazer a requisição. (<%= @erro %>)', classes: 'red'});
<% else %>
  $("#cost").val("<%= @cost %>");
<% end %>

app/views/rents/create.js.erb
<% if @rent.errors.any? %>
  <% @rent.errors.full_messages.each do |msg| %>
    M.toast({html: '<%= msg %>', classes: 'red'});
  <% end %>
<% else %>
  M.toast({html: 'Criado!', classes: 'green'});
<% end %>

app/views/rents/edit.html.erb
<div class="card">
  <div class="card-content">
  <h5 class="blue-text f20">Edit # <%= @rent.id %></h5>
    <%= render "form" %>
  </div>
</div>

app/views/rents/index.html.erb
<div class="card">
  <div class="card-content">
    <%= search_form_for @q, remote: true do |f| %>
      <div class="row">
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :id_eq  %>
            <%= f.label :id_eq, "Código" %>
          </div>
        </div>
        <div class="col s12 m12 l3">
          <div class="input-field">
            <%= f.select :pickup_date_null, [["Selecione", ''], ["Retirado", 0], ["Não Retirado", 1]] %> 
            <%= f.label :pickup_date_null, "Retiradas" %>
          </div>
        </div>
        <div class="col s12 m12 l3">
          <div class="input-field">
            <%= f.select :return_date_null, [["Selecione", ''], ["Entregues", 0], ["Não Entregues", 1]] %> 
            <%= f.label :return_date_null, "Devolução" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12 m12 l3">
          <div class="input-field">
            <%= f.search_field :end_date_lt, type: "date" %>
            <%= f.label :end_date_lt, "Término menor que" %>
          </div>
        </div>
        <div class="col s12 m12 l3">
          <div class="input-field">
            <%= f.search_field :pickup_date_lt, type: "date" %>
            <%= f.label :pickup_date_lt, "Retirada menor que" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12 m12 l12">
          <%= f.submit 'buscar', :class => 'btn shadow blue right', :id => "buscar" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="card">
  <div class="card-content">
    <%= link_to "Novo", new_rent_path, class: "btn green" %>
    <div id="rents_list">
      <%= render "list" %>
    </div>
  </div>
</div>

app/views/rents/index.js.erb
$("#rents_list").html("<%= j( render 'list' )%>");

app/views/rents/new.html.erb
<div class="card">
  <div class="card-content">
  <h5 class="blue-text f20">Nova Locação</h5>
    <%= render "form" %>
  </div>
</div>

app/views/rents/pickup_car.js.erb
<% if @rent.errors.any? %>
  <% @rent.errors.full_messages.each do |msg| %>
    M.toast({html: '<%= msg %>', classes: 'red'});
  <% end %>
<% else %>
  M.toast({html: 'Atualizado!', classes: 'green'});
  $("#buscar").trigger("click");
<% end %>

app/views/rents/return_car.js.erb
<% if @rent.errors.any? %>
  <% @rent.errors.full_messages.each do |msg| %>
    M.toast({html: '<%= msg %>', classes: 'red'});
  <% end %>
<% else %>
  M.toast({html: 'Atualizado!', classes: 'green'});
  $("#buscar").trigger("click");
<% end %>

app/views/rents/update.js.erb
<% if @rent.errors.any? %>
  <% @rent.errors.full_messages.each do |msg| %>
    M.toast({html: '<%= msg %>', classes: 'red'});
  <% end %>
<% else %>
  M.toast({html: 'Atualizado!', classes: 'green'});
<% end %>