config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  controller :people do
    post '/people/set_preferred/:id' => :set_preferred, as: :people_set_preferred
  end
  resources :people
  resources :automobiles
  resources :licenses
  controller :rents do
    get '/rents/calculate_cost' => :calculate_cost, as: :rents_calculate_cost
    post '/rents/pickup_car/:id' => :pickup_car, as: :rents_pickup_car
    post '/rents/return_car/:id' => :return_car, as: :rents_return_car
  end
  resources :rents

  root 'rents#index'
  get '*path' => redirect('/')
end

app/views/shared/_navbar.html.erb
<nav>
  <div class="nav-wrapper container">
    <a href="/" class="brand-logo ajax_logo animated flip"><img src="/images/icon.png" class="img-fluid width-64 height-64"></a>
    <a data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <% if current_user %>
        <li>
          <%= link_to "Locações", rents_path %>
        </li>
        <li>
          <%= link_to "Pessoas", people_path %>
        </li>
        <li>
          <%= link_to "Automóveis", automobiles_path %>
        </li>
        <li>
          <%= link_to "Habilitações", licenses_path %>
        </li>
        <li>
          <%= link_to "<i class='material-icons #{'menu-icon' if current_page?destroy_user_session_path}'>exit_to_app</i> <span class='hide-on-large-only'>Sair</span>".html_safe, destroy_user_session_path, class: "tooltipped", 'data-tooltip' => "Sair", :method => :delete, "data-position" =>"right" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <% if current_user %>
    <li>
      <%= link_to "Locações", rents_path %>
    </li>
    <li>
      <%= link_to "Pessoas", people_path %>
    </li>
    <li>
      <%= link_to "Automóveis", automobiles_path %>
    </li>
    <li>
      <%= link_to "Habilitações", licenses_path %>
    </li>
    <li>
      <%= link_to "<i class='material-icons #{'menu-icon' if current_page?destroy_user_session_path}'>exit_to_app</i> <span class='hide-on-large-only'>Sair</span>".html_safe, destroy_user_session_path, class: "tooltipped", 'data-tooltip' => "Sair", :method => :delete, "data-position" =>"right" %>
    </li>
  <% end %>
</ul>