config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  controller :people do
    post '/people/set_preferred/:id' => :set_preferred, as: :people_set_preferred
  end
  resources :people
  resources :automobiles
  resources :licenses
  controller :rents do
    get '/rents/calculate_cost' => :calculate_cost, as: :rents_calculate_cost
    post '/rents/pickup_car/:id' => :pickup_car, as: :rents_pickup_car
    post '/rents/return_car/:id' => :return_car, as: :rents_return_car
  end
  resources :rents

  root 'rents#index'
  get '*path' => redirect('/')
end

app/models/automobile.rb
# frozen_string_literal: true

class Automobile < ApplicationRecord
  enum kind: %i[car motorcycle vuc truck bus]

  has_many :rents

  validates_presence_of :cost, :color, :model, :license_plate, :kind

  scope :ordered, -> { order('automobiles.created_at desc') }

  def full_description
    "#{kind} #{model} (#{color}) - #{license_plate}"
  end

  def self.kind_to_select
    kinds.map do |r, _key|
      [I18n.t("automobile.kind.#{r}"), r]
    end
  end
end

app/controllers/automobiles_controller.rb
# frozen_string_literal: true

class AutomobilesController < ApplicationController
  before_action :set_automobile, only: %i[show edit update destroy]

  def index
    @q = Automobile.ransack(params[:q])
    @automobiles = @q.result
  end

  def edit; end

  def update
    @automobile.update(automobile_params)
    respond_to do |format|
      format.js
    end
  end

  def new
    @automobile = Automobile.new
  end

  def create
    @automobile = Automobile.new(automobile_params)
    if @automobile.save
      redirect_to edit_automobile_path(@automobile), notice: "#{@automobile.model} (#{@automobile.license_plate}) criado com sucesso!"
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy; end

  private

  def set_automobile
    @automobile = Automobile.find(params[:id])
  end

  def automobile_params
    params.require(:automobile).permit(:color, :model, :year, :license_plate, :kind, :cost)
  end
end

app/views/automobiles/_automobile.html.erb
<tr>
  <td>
    <%= automobile.color %>
  </td>
  <td>
    <%= automobile.model %>
  </td>
  <td>
    <%= automobile.year %>
  </td>
  <td>
    <%= automobile.license_plate %>
  </td>
  <td>
    <%= I18n.t("automobile.kind.#{automobile.kind}") %>
  </td>
  <td>
    <%= automobile.cost %>
  </td>
  <td>
    <%= link_to edit_automobile_path(automobile) do %>
    <i class="material-icons f20">edit</i>
    <% end %>
  </td>
</tr>

app/views/automobiles/_form.html.erb
<%= form_for [@automobile], remote: true do |f| %>
  <div class="row">
    <div class="input-field col s12 m6 l4">
      <%= f.text_field :color %>
      <label for="automobile_color">Cor</label>
    </div>
    <div class="input-field col s12 m6 l4">
      <%= f.text_field :model %>
      <label for="automobile_model">Modelo</label>
    </div>
    <div class="input-field col s12 m6 l4">
      <%= f.text_field :year %>
      <label for="automobile_year">Ano</label>
    </div>
    <div class="input-field col s12 m6 l4">
      <%= f.text_field :license_plate %>
      <label for="automobile_license_plate">Placa</label>
    </div>
    <div class="input-field col s12 m6 l4">
      <%= f.collection_select :kind, Automobile.kind_to_select, "last", "first", { prompt: "Selecione" } %>
      <%= f.label :kind, "Tipo" %>
    </div>
    <div class="input-field col s12 m6 l4">
      <%= f.text_field :cost %>
      <label for="automobile_cost">Custo</label>
    </div>
  </div>

  <div class="row">
    <div class="action">
      <button type="submit" class="btn blue right"><%= @automobile.new_record? ? 'Criar' : 'Atualizar' %></button>
    </div>
  </div>
<% end %>

app/views/automobiles/_list.html.erb
<table class="striped responsive-table f12">
  <thead>
    <tr>
      <th>Cor</th>
      <th>Modelo</th>
      <th>Ano</th>
      <th>Placa</th>
      <th>Tipo</th>
      <th>Custo</th>
      <th>#</th>
    </tr>
  </thead>
  <tbody>
    <%= render @automobiles %>
  </tbody>
</table>

app/views/automobiles/create.js.erb
<% if @automobile.errors.any? %>
  <% @automobile.errors.full_messages.each do |msg| %>
    M.toast({html: '<%= msg %>', classes: 'red'});
  <% end %>
<% else %>
  M.toast({html: 'Criado!', classes: 'green'});
<% end %>

app/views/automobiles/edit.html.erb
<div class="card">
  <div class="card-content">
  <h5 class="blue-text f20">Edit # <%= @automobile.id %></h5>
    <%= render "form" %>
  </div>
</div>

app/views/automobiles/index.html.erb
<div class="card">
  <div class="card-content">
    <%= search_form_for @q, remote: true do |f| %>
      <div class="row">
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :id_eq  %>
            <%= f.label :id_eq, "Código" %>
          </div>
        </div>
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :model_cont  %>
            <%= f.label :model_cont, "Modelo" %>
          </div>
        </div>
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :license_plate_cont  %>
            <%= f.label :license_plate_cont, "Placa" %>
          </div>
        </div>
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :color_cont  %>
            <%= f.label :color_cont, "Cor" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :kind_cont  %>
            <%= f.label :kind_cont, "Tipo" %>
          </div>
        </div>
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :cost_lt  %>
            <%= f.label :cost_lt, "Valor Menor Que" %>
          </div>
        </div>
        <div class="col s12 m6 l3">
          <div class="input-field">
            <%= f.search_field :cost_gt  %>
            <%= f.label :cost_gt, "Valor Maior Que" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12 m12 l12">
          <%= f.submit 'buscar', :class => 'btn shadow blue right', :id => "buscar" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="card">
  <div class="card-content">
    <%= link_to "Novo", new_automobile_path, class: "btn green" %>
    <div id="automobiles_list">
      <%= render "list" %>
    </div>
  </div>
</div>

app/views/automobiles/index.js.erb
$("#automobiles_list").html("<%= j( render 'list' )%>");
M.toast({html: '<%= pluralize(@automobiles.size, "resultado", "resultados") %>', classes: 'grey'});

app/views/automobiles/new.html.erb
<div class="card">
  <div class="card-content">
  <h5 class="blue-text f20">Novo Automóvel</h5>
    <%= render "form" %>
  </div>
</div>

app/views/automobiles/update.js.erb
<% if @automobile.errors.any? %>
  <% @automobile.errors.full_messages.each do |msg| %>
    M.toast({html: '<%= msg %>', classes: 'red'});
  <% end %>
<% else %>
  M.toast({html: 'Atualizado!', classes: 'green'});
<% end %>